[2022-08-29T20:01:08.493-0400] {processor.py:153} INFO - Started process (PID=14407) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:01:08.502-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:01:08.502-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:01:08.502-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:01:08.534-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:01:08.533-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:01:08.534-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:01:08.534-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:01:08.534-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:01:08.584-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.092 seconds
[2022-08-29T20:02:36.914-0400] {processor.py:153} INFO - Started process (PID=14492) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:02:36.923-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:02:36.923-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:02:36.923-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:02:36.951-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:02:36.951-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:02:36.952-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:02:36.952-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:02:36.952-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:02:37.004-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.091 seconds
[2022-08-29T20:04:01.080-0400] {processor.py:153} INFO - Started process (PID=14571) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:04:01.088-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:04:01.088-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:04:01.088-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:04:01.117-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:04:01.116-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:04:01.117-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:04:01.117-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:04:01.117-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:04:01.166-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.088 seconds
[2022-08-29T20:05:29.682-0400] {processor.py:153} INFO - Started process (PID=14652) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:05:29.690-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:05:29.691-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:05:29.691-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:05:29.719-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:05:29.719-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:05:29.720-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:05:29.719-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:05:29.720-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:05:29.769-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.088 seconds
[2022-08-29T20:06:55.076-0400] {processor.py:153} INFO - Started process (PID=14732) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:06:55.084-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:06:55.085-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:06:55.084-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:06:55.113-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:06:55.112-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:06:55.113-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:06:55.113-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:06:55.113-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:06:55.164-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.089 seconds
[2022-08-29T20:08:22.514-0400] {processor.py:153} INFO - Started process (PID=14815) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:08:22.523-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:08:22.524-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:08:22.524-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:08:22.553-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:08:22.552-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:08:22.553-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:08:22.553-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:08:22.553-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:08:22.604-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.091 seconds
[2022-08-29T20:09:52.203-0400] {processor.py:153} INFO - Started process (PID=14897) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:09:52.214-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:09:52.215-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:09:52.215-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:09:52.263-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:09:52.263-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:09:52.264-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:09:52.263-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:09:52.264-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:09:52.316-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.115 seconds
[2022-08-29T20:11:29.650-0400] {processor.py:153} INFO - Started process (PID=14987) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:11:29.659-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:11:29.659-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:11:29.659-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:11:29.688-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:11:29.687-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:11:29.688-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:11:29.688-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:11:29.688-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:11:29.737-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.088 seconds
[2022-08-29T20:12:59.600-0400] {processor.py:153} INFO - Started process (PID=15072) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:12:59.608-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:12:59.609-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:12:59.608-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:12:59.637-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:12:59.637-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:12:59.638-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:12:59.638-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:12:59.638-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:12:59.688-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.089 seconds
[2022-08-29T20:14:28.439-0400] {processor.py:153} INFO - Started process (PID=15152) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:14:28.447-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:14:28.448-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:14:28.448-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:14:28.475-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:14:28.475-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:14:28.476-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:14:28.476-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:14:28.476-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:14:28.525-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.087 seconds
[2022-08-29T20:16:09.588-0400] {processor.py:153} INFO - Started process (PID=15270) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:16:09.599-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:16:09.600-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:16:09.600-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:16:09.659-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:16:09.659-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:16:09.659-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:16:09.659-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:16:09.660-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:16:09.757-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.170 seconds
[2022-08-29T20:18:04.894-0400] {processor.py:153} INFO - Started process (PID=15390) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:18:04.905-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:18:04.906-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:18:04.905-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:18:04.940-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:18:04.940-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:18:04.941-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:18:04.941-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:18:04.941-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:18:05.010-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.118 seconds
[2022-08-29T20:19:52.265-0400] {processor.py:153} INFO - Started process (PID=15501) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:19:52.275-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:19:52.276-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:19:52.276-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:19:52.307-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:19:52.306-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:19:52.307-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:19:52.307-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:19:52.308-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:19:52.359-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.095 seconds
[2022-08-29T20:21:26.291-0400] {processor.py:153} INFO - Started process (PID=15586) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:21:26.299-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:21:26.300-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:21:26.300-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:21:26.329-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:21:26.328-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:21:26.329-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:21:26.329-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:21:26.329-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:21:26.378-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.088 seconds
[2022-08-29T20:22:50.406-0400] {processor.py:153} INFO - Started process (PID=15666) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:22:50.414-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:22:50.415-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:22:50.414-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:22:50.443-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:22:50.443-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:22:50.443-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:22:50.443-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:22:50.444-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:22:50.493-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.088 seconds
[2022-08-29T20:24:19.375-0400] {processor.py:153} INFO - Started process (PID=15747) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:24:19.384-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:24:19.384-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:24:19.384-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:24:19.413-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:24:19.412-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:24:19.413-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:24:19.413-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:24:19.413-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:24:19.462-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.088 seconds
[2022-08-29T20:26:00.470-0400] {processor.py:153} INFO - Started process (PID=15843) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:26:00.481-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:26:00.481-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:26:00.481-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:26:00.516-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:26:00.516-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:26:00.517-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:26:00.516-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:26:00.517-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:26:00.575-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.108 seconds
[2022-08-29T20:28:05.013-0400] {processor.py:153} INFO - Started process (PID=15961) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:28:05.023-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:28:05.024-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:28:05.023-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:28:05.052-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:28:05.051-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:28:05.052-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:28:05.052-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:28:05.052-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:28:05.102-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.090 seconds
[2022-08-29T20:29:45.847-0400] {processor.py:153} INFO - Started process (PID=16049) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:29:45.856-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:29:45.857-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:29:45.857-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:29:45.889-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:29:45.888-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:29:45.889-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:29:45.889-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:29:45.889-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:29:45.945-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2022-08-29T20:32:00.871-0400] {processor.py:153} INFO - Started process (PID=16171) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:32:00.882-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:32:00.882-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:32:00.882-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:32:00.917-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:32:00.917-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:32:00.918-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:32:00.917-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:32:00.918-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:32:00.974-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.104 seconds
[2022-08-29T20:34:04.517-0400] {processor.py:153} INFO - Started process (PID=16293) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:34:04.527-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:34:04.528-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:34:04.528-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:34:04.560-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:34:04.559-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:34:04.560-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:34:04.560-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:34:04.560-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:34:04.610-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.094 seconds
[2022-08-29T20:35:46.859-0400] {processor.py:153} INFO - Started process (PID=16413) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:35:46.874-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:35:46.876-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:35:46.876-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:35:46.926-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:35:46.926-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:35:46.927-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:35:46.927-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:35:46.927-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:35:47.012-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.155 seconds
[2022-08-29T20:37:36.298-0400] {processor.py:153} INFO - Started process (PID=16520) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:37:36.308-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:37:36.309-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:37:36.309-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:37:36.342-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:37:36.341-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:37:36.342-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:37:36.342-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:37:36.342-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:37:36.392-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.095 seconds
[2022-08-29T20:39:38.435-0400] {processor.py:153} INFO - Started process (PID=16630) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:39:38.445-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:39:38.446-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:39:38.446-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:39:38.489-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:39:38.488-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:39:38.489-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:39:38.489-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:39:38.490-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:39:38.548-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.114 seconds
[2022-08-29T20:41:23.687-0400] {processor.py:153} INFO - Started process (PID=16722) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:41:23.696-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:41:23.696-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:41:23.696-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:41:23.729-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:41:23.729-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:41:23.730-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:41:23.730-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:41:23.730-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:41:23.795-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.109 seconds
[2022-08-29T20:43:14.925-0400] {processor.py:153} INFO - Started process (PID=16821) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:43:14.934-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:43:14.935-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:43:14.935-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:43:14.967-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:43:14.966-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:43:14.968-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:43:14.967-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:43:14.968-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:43:15.018-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.094 seconds
[2022-08-29T20:45:14.279-0400] {processor.py:153} INFO - Started process (PID=16930) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:45:14.288-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:45:14.289-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:45:14.289-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:45:14.320-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:45:14.320-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:45:14.321-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:45:14.321-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:45:14.321-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:45:14.370-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.093 seconds
[2022-08-29T20:46:51.849-0400] {processor.py:153} INFO - Started process (PID=17017) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:46:51.857-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:46:51.858-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:46:51.858-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:46:51.887-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:46:51.886-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:46:51.887-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:46:51.887-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:46:51.887-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:46:51.937-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.089 seconds
[2022-08-29T20:48:48.589-0400] {processor.py:153} INFO - Started process (PID=17121) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:48:48.599-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:48:48.600-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:48:48.600-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:48:48.631-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:48:48.631-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:48:48.632-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:48:48.632-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:48:48.632-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:48:48.681-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.092 seconds
[2022-08-29T20:50:26.484-0400] {processor.py:153} INFO - Started process (PID=17210) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:50:26.492-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:50:26.492-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:50:26.492-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:50:26.520-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:50:26.520-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:50:26.521-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:50:26.521-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:50:26.521-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:50:26.571-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.088 seconds
[2022-08-29T20:52:03.298-0400] {processor.py:153} INFO - Started process (PID=17299) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:52:03.308-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:52:03.308-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:52:03.308-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:52:03.340-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:52:03.339-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:52:03.340-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:52:03.340-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:52:03.340-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:52:03.390-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.094 seconds
[2022-08-29T20:53:52.146-0400] {processor.py:153} INFO - Started process (PID=17393) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:53:52.157-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:53:52.160-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:53:52.158-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:53:52.207-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:53:52.207-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:53:52.208-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:53:52.208-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:53:52.208-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:53:52.265-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.121 seconds
[2022-08-29T20:55:52.516-0400] {processor.py:153} INFO - Started process (PID=17490) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:55:52.526-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:55:52.527-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:55:52.527-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:55:52.560-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:55:52.560-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:55:52.560-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:55:52.560-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:55:52.561-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:55:52.616-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.101 seconds
[2022-08-29T20:57:42.433-0400] {processor.py:153} INFO - Started process (PID=17587) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:57:42.443-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T20:57:42.444-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:57:42.444-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:57:42.483-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:57:42.482-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T20:57:42.483-0400] {logging_mixin.py:115} INFO - [2022-08-29T20:57:42.483-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T20:57:42.483-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T20:57:42.551-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.119 seconds
[2022-08-29T21:00:06.630-0400] {processor.py:153} INFO - Started process (PID=17738) to work on /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T21:00:06.641-0400] {processor.py:640} INFO - Processing file /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-08-29T21:00:06.641-0400] {logging_mixin.py:115} INFO - [2022-08-29T21:00:06.641-0400] {dagbag.py:508} INFO - Filling up the DagBag from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T21:00:06.674-0400] {logging_mixin.py:115} INFO - [2022-08-29T21:00:06.673-0400] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-08-29T21:00:06.674-0400] {logging_mixin.py:115} INFO - [2022-08-29T21:00:06.674-0400] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-08-29T21:00:06.674-0400] {processor.py:652} WARNING - No viable dags retrieved from /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-08-29T21:00:06.725-0400] {processor.py:161} INFO - Processing /Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.096 seconds
